# Github Actions CI: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    [pre-commit.ci] Apply automatic pre-commit fixes

repos:
  # Codespell: Spell checks the documentation
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["*.md"]

  # Prettier: Consistent formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [markdown]

  # Misc hooks: https://github.com/pre-commit/pre-commit-hooks#hooks-available
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Autoformat: Makes sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Trims trailing whitespace.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
        args: ['--maxkb=20000'] # 20MB
